### ISSUE TITLE
Untangle wait from deletion of cluster objects

### ISSUE THREAD

**Issue by ormergi** [kiagnose/kiagnose#18]
Following https://github.com/kiagnose/kiagnose/pull/9/commits/f9a3039e29e0751378131988e0ecd8dd7a0cdad2#r851711235, 
waiting for an object to dispose from the cluster should be extracted to its own function.
It will improve deletion of cluster objects more efficient, as it enables sending few delete requests
before waiting for them to dispose.

**Comment by EdDev** [comment]
@ormergi , is this issue still relevant?
If it is, please update with ref on what would you suggest to change.

**Comment by ormergi** [comment]
Thanks for the heads up, it seems its not relevant anymore.
