### ISSUE TITLE
Add support for granting the checkup with permissions from Roles.

### ISSUE THREAD

**Issue by ormergi** [kiagnose/kiagnose#20]
It is possible for the user to specify the `ClusterRole`'s it expects the framework to grant the checkup with.

Supporting Roles will also enable the user to grant the checkup with permissions from an already exist `Role` (from another namespace), instead of tailoring a `ClusterRole` just to have that Role permissions.

**Comment by EdDev** [comment]
IIUC, the suggestion is to copy a role from another NS?
This feels like a hack to me.

There has been a request to provide the working namespace in advance. Perhaps that is an option we can consider and instruct the admin to set on it the required roles.

The option which is closer to your original suggestion can be to define template working namespaces, which are used to just be copied fully to running instances. But this is very odd and probably hard to keep "clean". How would we make sure no one touches these NS/s?
The previous option seems simpler to me.

**Comment by ormergi** [comment]
What I had in mind is reading each Role `rules` the user provided, and create single role with all the rules inside the checkup 
namespace.
Whether the "target" namespace for the checkup is provided or not, it will make sure "no harm is being done" to already exists
Roles, Kiagnose shouldn't have write permissions to the required Roles.

> There has been a request to provide the working namespace in advance. Perhaps that is an option we can consider and instruct the admin to set on it the required roles.

Instructing the admin to set Roles is quite similar to what we support today with `ClusterRoles`.
From what I understand the advantage might be that Kiagnose wont require `ClusterRoles` read/write permissions.

IMO supporting Roles should not be restricted only for this use case.

> The option which is closer to your original suggestion can be to define template working namespaces, which are used to just be copied fully to running instances. But this is very odd and probably hard to keep "clean". How would we make sure no one touches these NS/s?

I dont understand what you mean by "..define template working namespaces, which are used to just be copied fully to running instances" could you please elaborate or provide an example/ref?

**Comment by orelmisan** [comment]
After PR #150 was merged, this issue is no longer relevant, because the checkup's Job is using a ServiceAccount which should be pre-bound to Role and / or ClusterRole objects.
